import { Skills } from "@/src/types/investigator";

export const SKILLS_BASE: Skills[] = [
  {name: "Antropologia", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Arcos", baseValue: 15, group: "Combate (Armas e Luta)"},
  {name: "Armas Pesadas", baseValue: 10, group: "Combate (Armas e Luta)"},
  {name: "Arqueologia", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Arremessar", baseValue: 20, group: "Combate (Armas e Lutas)"},
  {name: "Arte e Ofício", baseValue: 5, group: "Técnicas e Operacionais"},
  {name: "Artilharia", baseValue: 1, group: "Combate (Armas e Luta)"},
  {name: "Astronomia", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Atuação", baseValue: 5, group: "Sociais e Comunicação"},
  {name: "Avaliação", baseValue: 5, group: "Investigação e Percepção"},
  {name: "Belas Artes", baseValue: 5, group: "Técnicas e Operacionais"},
  {name: "Biologia", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Botânica", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Briga", baseValue: 25, group: "Combate (Armas e Luta)"},
  {name: "Cavalgar", baseValue: 5, group: "Físicas e Movimentação"},
  {name: "Charme", baseValue: 15, group: "Sociais e Comunicação"},
  {name: "Chaveiro", baseValue: 1, group: "Técnicas e Operacionais"},
  {name: "Chicotes", baseValue: 5, group: "Combate (Armas e Luta)"},
  {name: "Ciência", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Ciência Forense", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Conhecimento", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Consertos Elétricos", baseValue: 10, group: "Técnicas e Operacionais"},
  {name: "Consertos Mecânicos", baseValue: 10, group: "Técnicas e Operacionais"},
  {name: "Contabilidade", baseValue: 5, group: "Acadêmicas e Ciências"},
  {name: "Criptografia", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Demolições", baseValue: 1, group: "Técnicas e Operacionais"},
  {name: "Direito", baseValue: 5, group: "Acadêmicas e Ciências"},
  {name: "Dirigir Automóveis", baseValue: 20, group: "Técnicas e Operacionais"},
  {name: "Disfarce", baseValue: 5, group: "Técnicas e Operacionais"},
  {name: "Encontrar", baseValue: 25, group: "Investigação e Percepção"},
  {name: "Engenharia", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Escalar", baseValue: 20, group: "Físicas e Movimentação"},
  {name: "Espingardas", baseValue: 25, group: "Combate (Armas e Luta)"},
  {name: "Escutar", baseValue: 20, group: "Investigação e Percepção"},
  {name: "Espadas", baseValue: 20, group: "Combate (Armas e Luta)"},
  {name: "Esquivar", baseValue: 0, group: "Combate (Armas e Luta)"},
  {name: "Falsificação", baseValue: 5, group: "Técnicas e Operacionais"},
  {name: "Farmácia", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Física", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Fotografia", baseValue: 5, group: "Técnicas e Operacionais"},
  {name: "Furtividade", baseValue: 20, group: "Físicas e Movimentação"},
  {name: "Garrote", baseValue: 15, group: "Combate (Armas e Luta)"},
  {name: "Geologia", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Hipnose", baseValue: 1, group: "Técnicas e Operacionais"},
  {name: "História", baseValue: 5, group: "Acadêmicas e Ciências"},
  {name: "Intimidação", baseValue: 15, group: "Sociais e Comunicação"},
  {name: "Lábia", baseValue: 5, group: "Sociais e Comunicação"},
  {name: "Lanças", baseValue: 20, group: "Combate (Armas e Luta)"},
  {name: "Lança-Chamas", baseValue: 10, group: "Combate (Armas e Luta)"},
  {name: "Leitura Labial", baseValue: 1, group: "Investigação e Percepção"},
  {name: "Língua (Nativa)", baseValue: 0, group: "Sociais e Comunicação"},
  {name: "Língua (Outra)", baseValue: 1, group: "Sociais e Comunicação"},
  {name: "Machados", baseValue: 15, group: "Combate (Armas e Luta)"},
  {name: "Manguais", baseValue: 10, group: "Combate (Armas e Luta)"},
  {name: "Matemática", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Medicina", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Mergulho", baseValue: 1, group: "Físicas e Movimentação"},
  {name: "Meteorologia", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Metralhadoras", baseValue: 10, group: "Combate (Armas e Luta)"},
  {name: "Motosserras", baseValue: 10, group: "Combate (Armas e Luta)"},
  {name: "Mundo Natural", baseValue: 10, group: "Acadêmicas e Ciências"},
  {name: "Mythos de Cthulhu", baseValue: 0, group: "Especiais / Mythos"},
  {name: "Natação", baseValue: 20, group: "Físicas e Movimentação"},
  {name: "Navegação", baseValue: 10, group: "Técnicas e Operacionais"},
  {name: "Nível de Crédito", baseValue: 0, group: "Sociais e Comunicação"},
  {name: "Ocultismo", baseValue: 5, group: "Acadêmicas e Ciências"},
  {name: "Operar Maquinário Pesado", baseValue: 1, group: "Técnicas e Operacionais"},
  {name: "Persuasão", baseValue: 10, group: "Sociais e Comunicação"},
  {name: "Pilotar", baseValue: 1, group: "Técnicas e Operacionais"},
  {name: "Pistolas", baseValue: 20, group: "Combate (Armas e Luta)"},
  {name: "Prestidigitação", baseValue: 10, group: "Técnicas e Operacionais"},
  {name: "Primeiros Socorros", baseValue: 30, group: "Técnicas e Operacionais"},
  {name: "Psicanálise", baseValue: 1, group: "Investigação e Percepção"},
  {name: "Psicologia", baseValue: 10, group: "Investigação e Percepção"},
  {name: "Química", baseValue: 1, group: "Acadêmicas e Ciências"},
  {name: "Rastrear", baseValue: 10, group: "Investigação e Percepção"},
  {name: "Rifles", baseValue: 25, group: "Combate (Armas e Luta)"},
  {name: "Saltar", baseValue: 20, group: "Físicas e Movimentação"},
  {name: "Sobrevivência", baseValue: 10, group: "Físicas e Movimentação"},
  {name: "Submetralhadoras", baseValue: 15, group: "Combate (Armas e Luta)"},
  {name: "Treinar Animais", baseValue: 5, group: "Técnicas e Operacionais"},
  {name: "Usar Bibliotecas", baseValue: 20, group: "Investigação e Percepção"},
  {name: "Zoologia", baseValue: 1, group: "Acadêmicas e Ciências"},
]